# workflow name
name: release

# on events
on:
  release:
    types:
      - created

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code inside the workspace directory of the runner
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # step 2: run tests
      - name: Test
        run: go test -v ./...

      # step 3: generate build files and dump inside the workspace directory of the runner
      - name: Generate build files
        uses: thatisuday/go-build-action@v1
        with:
          platforms: "linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64"
          package: ""
          name: "versionbump"
          compress: "false"
          dest: "dist"

      # step 3: Copy build-artifacts in the GitHub release
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"