name: Upload Go binaries

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Build
        run: env GOOS=linux GOARCH=arm64 go build -o versionbump-linux-arm64 .
        run: env GOOS=linux GOARCH=amd64 go build -o versionbump-linux-amd64 .
        run: env GOOS=darwin GOARCH=arm64 go build -o versionbump-darwin-arm64 .
        run: env GOOS=darwin GOARCH=amd64 go build -o versionbump-darwin-amd64 .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            versionbump-linux-arm64
            versionbump-linux-amd64
            versionbump-darwin-arm64
            versionbump-darwin-amd64
